<?php

return [
    'APP_NAME' => 'Direktori Litbang',
    'COMPANY_AREA' => 'Kabupaten Teluk Bintuni',
    'COMPANY' => 'Badan Penelitian dan Pengembangan Teluk Bintuni',
    'DOC_CATEGORIES' => [
        'REGULATION' => 'Perda & Perbup',
        'RND' => 'Litbang',
        'PLANNING' => 'Perencanaan',
    ],
    'DOC_CATEGORY_PERDA_PERBUP' => 'REGULATION',
    'DOC_CATEGORY_LITBANG' => 'RND',
    'DOC_CATEGORY_PLANNING' => 'PLANNING',
    'DOC_STATUSES' => [
        '0' => 'Draft',
        '1' => 'Approved',
        '2' => 'Published',
    ],
    'DOC_STATUS_DRAFT' => '0',
    'DOC_STATUS_APPROVED' => '1',
    'DOC_STATUS_PUBLISHED' => '2',
    'USER_TYPES' => [
        '0' => 'Administrator',
        '1' => 'Operator',
        '2' => 'Validator',
        '3' => 'Publisher',
    ],
    'USER_TYPE_ADMINISTRATOR' => '0',
    'USER_TYPE_OPERATOR' => '1',
    'USER_TYPE_VALIDATOR' => '2',
    'USER_TYPE_PUBLISHER' => '3',
    'PASSWORD_RESET_EXPIRE' => 3600,
    'EMAIL_DISPLAY_NAME' => 'Admin Direktori Litbang',
    'EMAIL_HOST' => 'smtp.gmail.com',
    'EMAIL_USERNAME' => 'litbang.telukbintuni@gmail.com',
    'EMAIL_PASSWORD' => 'direktorilitbang',
    'EMAIL_PORT' => 465,
    'EMAIL_ENCRYPTION' => 'ssl',
    'EMAIL_TIMEOUT' => 300,
    'DOCUMENTS_DIR' => 'documents/',
    'DOCUMENTS_URL' => 'http://localhost/litbang/web/documents/',
    'UPLOAD_DIR' => '@uploadDirectory/documents/',
];
